#/usr/bin/env perl
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec du texte utilisant Free Type
# Drawing text using Free Type fonts
#

use GD:from<Perl5>;
use MIME::Base64;

my $name   = '07-free-type-generic';
my $width  = 500;
my $height = 350;
my $im     = GD::Image.new($width, $height);
my $white  = $im.colorAllocate(255, 255, 255);
my $black  = $im.colorAllocate(  0,   0,   0);
my $red    = $im.colorAllocate(255,   0,   0);
my $blue   = $im.colorAllocate(  0,   0, 255);
my $fontpath = "sans";
my $fontalt  = "serif";
my $fontsize = 10;
my @result;

# 1: use generic font names
my $config = $im.useFontConfig(1);

@result = $im.stringFT($black, $fontpath, $fontsize,  π/2, 20, 110, "Vertical climb"); dump_res(@result);
@result = $im.stringFT($black, $fontpath, $fontsize,  π/4, 30, 120, "Zoom climb"    ); dump_res(@result);
@result = $im.stringFT($black, $fontpath, $fontsize,  0  , 40, 130, "Level flight"  ); dump_res(@result);
@result = $im.stringFT($black, $fontpath, $fontsize, -π/4, 30, 140, "Steep dive"    ); dump_res(@result);
@result = $im.stringFT($black, $fontpath, $fontsize, -π/2, 20, 150, "Vertical dive" ); dump_res(@result);

my $str1 = q :to<EOF>;
À l'Haÿ-les-Roses, rue Valentin Haüy,
vous êtes à côté de l'abîme où des pâtres naïfs
brûlèrent çà et là des œufs de Pâques à Noël.
EOF
my $str2 = q :to<EOF>;
Pfffff ! Lorsque le souffle du vent
fléchit dans le fjord, il est en effet
difficile de se faufiler.
EOF
@result = $im.stringFT($blue, $fontalt , $fontsize, 0, 10, 250, $str1); dump_res(@result);
@result = $im.stringFT($red , $fontalt , $fontsize, 0, 10, 310, $str2); dump_res(@result);

"$name.png".IO.spurt($im.png);

my $png =  MIME::Base64.encode($im.png);
"$name.html".IO.spurt(qq :to/EOF/);
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF

sub dump_res(@val) {
  if @val.elems == 8 {
    for @val -> $val {
      printf " %3d", $val;
    }
    print "\n";
  }
  else {
    print "**** some error: usually, font not found\n";
  }
}

=begin POD

=head1 NAME

07-free-type-generic.raku - drawing text using Free Type fonts

=head1 SYNOPSIS

  raku    07-free-type-generic.raku
  display 07-free-type-generic.png
  firefox 07-free-type-generic.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing  various texts using Free Type (or True Type) fonts.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Raku modules C<Inline::Perl5> and C<MIME::Base64>.

Perl module C<GD>.

=head1 BUGS AND PROBLEMS

The error code  produced by method C<stringFT> is  not caught, leading
to a potentially misleading error message.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end POD
