#/usr/bin/env perl
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec du texte utilisant Free Type
# Drawing text using Free Type fonts
#

use GD:from<Perl5>;
use MIME::Base64;

my $name   = '08-bounding-box';
my $width  = 500;
my $height = 350;
my $im     = GD::Image.newTrueColor($width, $height);
my $white  = $im.colorAllocate(255, 255, 255);
my $black  = $im.colorAllocate(  0,   0,   0);
my $red    = $im.colorAllocate(255,   0,   0);
my $blue   = $im.colorAllocate(  0,   0, 255);
my $grey-opaque = $im.colorAllocateAlpha(224, 224, 224,   0);
my $grey-transp = $im.colorAllocateAlpha(192, 192, 192,  64);
my $fontpath = "sans";
my $fontalt  = "serif";
my $fontsize = 10;
my @result;

# 1: use generic font names
my $config = $im.useFontConfig(1);

# True Color picture: you need to paint the background
$im.filledRectangle(0, 0, $width - 1, $height - 1, $white);

@result = $im.stringFT($black, $fontpath, $fontsize,  π/2, 20, 110, "Vertical climb"); bounding(@result);
@result = $im.stringFT($black, $fontpath, $fontsize,  π/4, 30, 120, "Zoom climb"    ); bounding(@result);
@result = $im.stringFT($black, $fontpath, $fontsize,  0  , 40, 130, "Level flight"  ); bounding(@result);
@result = $im.stringFT($black, $fontpath, $fontsize, -π/4, 30, 140, "Steep dive"    ); bounding(@result);
@result = $im.stringFT($black, $fontpath, $fontsize, -π/2, 20, 150, "Vertical dive" ); bounding(@result);

my $str1 = q :to<EOF>;
À l'Haÿ-les-Roses, rue Valentin Haüy,
vous êtes à côté de l'abîme où des pâtres naïfs
brûlèrent çà et là des œufs de Pâques à Noël.
EOF
my $str2 = q :to<EOF>;
Pfffff ! Lorsque le souffle du vent
fléchit dans le fjord, il est en effet
difficile de se faufiler.
EOF

# No alpha channel: three-step process with possible race condition
@result = GD::Image.stringFT($blue, $fontalt , $fontsize, 0,  10, 250, $str1);
$im.filledRectangle(|@result[0, 1, 4, 5], $grey-opaque);
@result = $im.stringFT($blue, $fontalt , $fontsize, 0,  10, 250, $str1);

# With alpha channel: two-step process, without race condition
@result = $im.stringFT($red , $fontalt , $fontsize, 0, 10, 310, $str2);
$im.filledRectangle(|@result[0, 1, 4, 5], $grey-transp);

"$name.png".IO.spurt($im.png);

my $png =  MIME::Base64.encode($im.png);
"$name.html".IO.spurt(qq :to/EOF/);
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF

sub bounding(@corners) {
  if @corners.elems == 8 {
    my $poly = GD::Polygon.new;
    for 0, 2, 4, 6 -> $i {
      $poly.addPt(@corners[$i], @corners[$i + 1]);
    }
    $im.filledPolygon($poly, $grey-transp);
  }
  else {
    print "**** some error: usually, font not found\n";
  }
}

=begin POD

=head1 NAME

08-bounding-box.raku - drawing text using Free Type fonts, on a light grey background

=head1 SYNOPSIS

  raku    08-bounding-box.raku
  display 08-bounding-box.png
  firefox 08-bounding-box.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing various texts using Free Type (or True Type) fonts.  The texts
appear on  a light grey  background, reflecting the bounding  boxes of
the texts.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Raku modules C<Inline::Perl5> and C<MIME::Base64>.

Perl module C<GD>.

=head1 PROBLEMS AND ISSUES

=head2 Error Code

The error code  produced by method C<stringFT> is  not caught, leading
to a potentially misleading error message.

=head2 Race Condition

When drawing the bounding box with an opaque colour, you need a 3-step
process:

  @bounds = GD::Image.stringFT(...); # 1
  $im.rectangle(..., $grey-opaque);  # 2
  @bounds = $im.stringFT(...);       # 3

If, between  step 1 and  step 3, another  process installs a  new Free
Type font, the bounding box in step  3 can be quite different from the
bounding  box computed  in step  1.  The rectangle  in step  2 can  be
ill-fitting  to the  text in  step  3. This  is a  race condition.  To
prevent  this race  condition, you  should use  colours with  an alpha
channel.

  @bounds = $im.stringFT(...);       # 1
  $im.rectangle(..., $grey-transp);  # 2

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end POD
