#!/usr/bin/env perl
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin utilisant l'auto-massicotage (auto-crop)
# Picture with auto-crop
#

use GD:from<Perl5>;
use MIME::Base64;

my $name   = '09-auto-crop';
my $width  = 151;
my $height = 151;
my $im     = GD::Image.new($width, $height);
my $white  = $im.colorAllocate(255, 255, 255);
my $black  = $im.colorAllocate(  0,   0,   0);

spiral( 20,  20, 33);
spiral(130, 130, 32);
$im.ellipse( 10,  80, 40, 40, $black);
$im.ellipse(-10, 120, 40, 40, $black);
$im.ellipse(140,  30, 40, 40, $black);
$im.ellipse(160,  70, 40, 40, $black);
$im.rectangle(70, -20, 100,  10, $black);
$im.rectangle(50, 140,  80, 170, $black);

"$name.png".IO.spurt($im.png);

my $png =  MIME::Base64.encode($im.png);
"$name.html".IO.spurt(qq :to/EOF/);
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF

sub spiral($cx, $cy, $n) {

  my ($xa, $ya) = ($cx, $cy);
  my ($cos_theta, $sin_theta) = (1, 0);
  for (1 .. $n) -> $r {
    my ($xd, $yd) = ($xa, $ya);
    $xa = $cx + $r * $cos_theta;
    $ya = $cy + $r * $sin_theta;
    $im.line($xd, $yd, $xa, $ya, $black);
    ($cos_theta, $sin_theta) = (- $sin_theta, $cos_theta);
  }
}

=begin POD

=head1 NAME

09-auto-crop.raku - drawing a picture with auto-crop

=head1 SYNOPSIS

  raku    09-auto-crop.raku
  display 09-auto-crop.png
  firefox 09-auto-crop.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing various patterns straddling a canvas border.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Raku modules C<Inline::Perl5> and C<MIME::Base64>.

Perl module C<GD>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end POD
