#!/usr/bin/env raku
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessiner une spirale avec un style très long
# Drawing a spiral with a huge style
#

use GD:from<Perl5>;
use MIME::Base64;

my $name   = '22-long-style';
my $size   = 150;
my $im     = GD::Image.new($size, $size);
my $white  = $im.colorAllocate(255, 255, 255);
my $red    = $im.colorAllocate(255,   0,   0);
my $blue   = $im.colorAllocate(  0,   0, 255);
my $grey   = $im.colorAllocate(240, 240, 240);
my $black  = $im.colorAllocate(  0,   0,   0);

my @style = ();
for (0..256) -> $n {
  my $str = sprintf('%08b', $n);
  for (0..7) -> $pos {
    my $digit = $str.substr($pos, 1);
    if $digit eq '0' {
      @style.push($grey, $blue, $blue, $grey);
    }
    else {
      @style.push($grey, $red, $red, $grey);
    }
  }
  @style.push($black);
}
$im.setStyle(|@style);
say "size ", @style.elems;

my $x  = ($size / 2).Int;
my $y  = $x;
my $vx = 1;
my $vy = 0;

loop (my $l = 1; $l < $size; $l += 2) {
  $im.line($x, $y, $x + $vx × $l, $y + $vy × $l, gdStyled);
  $x += $vx × $l;
  $y += $vy × $l;
  ($vx, $vy) = ($vy, -$vx);
}

"$name.png".IO.spurt($im.png);

my $png =  MIME::Base64.encode($im.png);
"$name.html".IO.spurt(qq :to/EOF/);
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF

=begin POD

=head1 NAME

22-long-style.raku - draw a spiral with a long style

=head1 SYNOPSIS

  raku    22-long-style.raku
  display 22-long-style.png
  firefox 22-long-style.html

=head1 DESCRIPTION

This program generates a PNG file and an HTML file with a spiral using
a style containing many pixels.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Raku modules C<Inline::Perl5> and C<MIME::Base64>.

Perl module C<GD>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end POD
