#!/usr/bin/env raku
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec des lignes basiques
# Drawing with basic lines
#

use GD::Raw;
use MIME::Base64;
use NativeHelpers::Blob;

my $name   = '00-basic-lines';
my $width  = 120;
my $height =  50;
my $im     = gdImageCreate($width, $height);
LEAVE gdImageDestroy($im) if $im;
my $white  = gdImageColorAllocate($im, 255, 255, 255);
my $black  = gdImageColorAllocate($im,   0,   0,   0);
my $red    = gdImageColorAllocate($im, 255,   0,   0);
my $blue   = gdImageColorAllocate($im,   0,   0, 255);

gdImageLine($im, 10, 10, 100, 10, $red);
gdImageLine($im, 10, 20, 100, 20, $blue);
gdImageLine($im, 10, 30, 100, 40, $black);

my $fh = fopen("$name.png", "wb");
return 0 unless $fh;
gdImagePng($im, $fh);
fclose($fh) if $fh;

my $png-data;
my int32 $size;
my $ptr  = gdImagePngPtr($im, $size);
my $blob = blob-from-pointer($ptr, elems => $size, type => Blob[int8]);
my $png  =  MIME::Base64.encode($blob);
gdFree($ptr);
"$name.html".IO.spurt(qq :to/EOF/);
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>External PNG file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF

=begin POD

=head1 NAME

00-basic-lines.raku - draw basic lines

=head1 SYNOPSIS

  raku    00-basic-lines.raku
  display 00-basic-lines.png
  #firefox 00-basic-lines.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing  basic lines  (various colours,  single thickness,  no special
patterns such as dashed line or dotted line).

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Raku modules C<GD::Raw> and C<MIME::Base64>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end POD
