#/usr/bin/env raku
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec des lignes d'épaisseurs variées
# Drawing lines with different thicknesses
#

use GD::Raw;
use MIME::Base64;

my $name   = '01-thick-lines';
my $width  = 120;
my $height =  50;
my $im     = gdImageCreate($width, $height);
LEAVE gdImageDestroy($im) if $im;
my $white  = gdImageColorAllocate($im, 255, 255, 255);
my $black  = gdImageColorAllocate($im,   0,   0,   0);
my $red    = gdImageColorAllocate($im, 255,   0,   0);
my $blue   = gdImageColorAllocate($im,   0,   0, 255);

gdImageLine($im, 10, 10, 100, 10, $red);
gdImageSetThickness($im, 2);
gdImageLine($im, 10, 20, 100, 20, $blue);
gdImageSetThickness($im, 3);
gdImageLine($im, 10, 30, 100, 40, $black);

my $fh = fopen("$name.png", "wb");
return 0 unless $fh;
gdImagePng($im, $fh);
fclose($fh) if $fh;

#my $png-data;
#gdImagePngPrt($im, $png-data);
#my $png =  MIME::Base64.encode($png-data);
#"$name.html".IO.spurt(qq :to/EOF/);
#<html>
#<head><title>Example of graphic file generated by GD</title></head>
#<body>
#<h1>Graphic file</h1>
#<img src='$name.png'>
#<h1>Embedded PNG data</h1>
#<img src='data:image/png;base64,$png'>
#</body>
#</html>
#EOF

=begin POD

=head1 NAME

01-thick-lines.raku - draw lines with various thicknesses

=head1 SYNOPSIS

  raku    01-thick-lines.raku
  display 01-thick-lines.png
  #firefox 01-thick-lines.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing  lines  (various  colours,  various  thicknesses,  no  special
patterns such as dashed line or dotted line).

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Raku modules C<GD::Raw> and C<MIME::Base64>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end POD
