#/usr/bin/env raku
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec des cercles et des rectangles
# Drawing circles and rectangles
#

use GD::Raw;
use MIME::Base64;

my $name   = '03-circles-rectangles';
my $width  = 200;
my $height =  50;
my $im     = gdImageCreate($width, $height);
LEAVE gdImageDestroy($im) if $im;
my $white  = gdImageColorAllocate($im, 255, 255, 255);
my $black  = gdImageColorAllocate($im,   0,   0,   0);
my $red    = gdImageColorAllocate($im, 255,   0,   0);
my $blue   = gdImageColorAllocate($im,   0,   0, 255);

gdImageLine($im, 0, 10, 190, 30, $black);
gdImageFilledEllipse(  $im, 10,  20,  20, 20, $white);
#dImageEllipse(        $im, 10,  20,  20, 20, $blue);
gdImageFilledRectangle($im, 30,  10,  50, 30, $white);
#dImageRectangle(      $im, 30,  10,  50, 30, $blue);
gdImageFilledEllipse(  $im, 70,  20,  20, 20, $red);
gdImageFilledRectangle($im, 90,  10, 110, 30, $red);
gdImageSetThickness($im, 3);
gdImageFilledEllipse(  $im, 130,  20,  20, 20, $white);
#dImageEllipse(        $im, 130,  20,  20, 20, $blue);
gdImageFilledRectangle($im, 150,  10, 170, 30, $white);
#dImageRectangle(      $im, 150,  10, 170, 30, $blue);

my $fh = fopen("$name.png", "wb");
return 0 unless $fh;
gdImagePng($im, $fh);
fclose($fh) if $fh;

#my $png-data;
#gdImagePngPrt($im, $png-data);
#my $png =  MIME::Base64.encode($png-data);
my $png =  qx/base64 wip.png/;
"$name.html".IO.spurt(qq :to/EOF/);
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF

=begin POD

=head1 NAME

03-circles-rectangles.raku - draw circles and rectangles

=head1 SYNOPSIS

  raku    03-circles-rectangles.raku
  display 03-circles-rectangles.png
  #firefox 03-circles-rectangles.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing circles and rectangles (or squares).

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Raku modules C<GD::Raw> and C<MIME::Base64>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end POD
