#/usr/bin/env raku
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec des cercles et des rectangles plus du texte
# Drawing circles and rectangles with labels
#

use GD::Raw;
use MIME::Base64;
use NativeHelpers::Blob;

my $name   = '04-labels';
my $width  = 200;
my $height =  50;
my $im     = gdImageCreate($width, $height);
LEAVE gdImageDestroy($im) if $im;
my $white  = gdImageColorAllocate($im, 255, 255, 255);
my $black  = gdImageColorAllocate($im,   0,   0,   0);
my $red    = gdImageColorAllocate($im, 255,   0,   0);
my $blue   = gdImageColorAllocate($im,   0,   0, 255);

gdImageLine($im, 0, 10, 190, 30, $black);
gdImageFilledEllipse(  $im, 10,  20,  20, 20, $white);
gdImageEllipse(        $im, 10,  20,  20, 20, $blue);
gdImageFilledRectangle($im, 30,  10,  50, 30, $white);
gdImageRectangle(      $im, 30,  10,  50, 30, $blue);
gdImageFilledEllipse(  $im, 70,  20,  20, 20, $red);
gdImageFilledRectangle($im, 90,  10, 110, 30, $red);
gdImageSetThickness($im, 3);
gdImageFilledEllipse(  $im, 130,  20,  20, 20, $white);
gdImageEllipse(        $im, 130,  20,  20, 20, $blue);
gdImageFilledRectangle($im, 150,  10, 170, 30, $white);
gdImageRectangle(      $im, 150,  10, 170, 30, $blue);
#gdImageString($im, gdSmallFont,        5, 15, '01', $black);
#gdImageString($im, gdMediumBoldFont,  35, 15, '02', $black);
#gdImageString($im, gdLargeFont,      153, 13, '03', $black);

my $fh = fopen("$name.png", "wb");
return 0 unless $fh;
gdImagePng($im, $fh);
fclose($fh) if $fh;

my $png-data;
my int32 $size;
my $ptr  = gdImagePngPtr($im, $size);
my $blob = blob-from-pointer($ptr, elems => $size, type => Blob[int8]);
my $png  =  MIME::Base64.encode($blob);
gdFree($ptr);
"$name.html".IO.spurt(qq :to/EOF/);
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF

=begin POD

=head1 NAME

04-labels.raku - print labels inside circles and rectangles

=head1 SYNOPSIS

  raku    04-labels.raku
  display 04-labels.png
  #firefox 04-labels.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing  circles and  rectangles (or  squares) and  labels inside  the
circles and rectangles.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Raku modules C<GD::Raw> and C<MIME::Base64>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end POD
