#!/usr/bin/env raku
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec du texte utilisant Free Type
# Drawing text using Free Type fonts
#

use GD::Raw;
use MIME::Base64;
use NativeCall;
use NativeHelpers::Blob;

my $name   = '05-free-type';
my $width  = 500;
my $height = 450;
my $im     = gdImageCreate($width, $height);
LEAVE gdImageDestroy($im) if $im;
my $white  = gdImageColorAllocate($im, 255, 255, 255);
my $black  = gdImageColorAllocate($im,   0,   0,   0);
my $red    = gdImageColorAllocate($im, 255,   0,   0);
my $blue   = gdImageColorAllocate($im,   0,   0, 255);

my $fontpath = "/usr/share/fonts/truetype/freefont/FreeSans.ttf";
my $fontalt  = "/usr/share/fonts/truetype/freefont/FreeSerif.ttf";
my $fontsize = 10e0;

my $rc = gdFontCacheSetup();
LEAVE gdFontCacheShutdown();
# zero : do not use generic font names
my $config = gdFTUseFontConfig(0);

my @bound-rect := CArray[int32].new;
@bound-rect[7] = 0; # to allocate room for 8 integers

my $err;
$err = gdImageStringFT($im, @bound-rect, $black, $fontpath, $fontsize,  π/2, 10, 110, "Vertical climb"); dump-res($err, @bound-rect);
$err = gdImageStringFT($im, @bound-rect, $black, $fontpath, $fontsize,  π/4, 20, 120, "Zoom climb"    ); dump-res($err, @bound-rect);
$err = gdImageStringFT($im, @bound-rect, $black, $fontpath, $fontsize,  0e0, 30, 130, "Level flight"  ); dump-res($err, @bound-rect);
$err = gdImageStringFT($im, @bound-rect, $black, $fontpath, $fontsize, -π/4, 20, 140, "Steep dive"    ); dump-res($err, @bound-rect);
$err = gdImageStringFT($im, @bound-rect, $black, $fontpath, $fontsize, -π/2, 10, 150, "Vertical dive" ); dump-res($err, @bound-rect);

my $str1 = q :to<EOF>;
À l'Haÿ-les-Roses, rue Valentin Haüy,
vous êtes à côté de l'abîme où des pâtres naïfs
brûlèrent çà et là des œufs de Pâques à Noël.
EOF
my $str2 = q :to<EOF>;
Pfffff ! Lorsque le souffle du vent
fléchit dans le fjord, il est en effet
difficile de se faufiler.
EOF

$err = gdImageStringFT($im, @bound-rect, $blue, $fontalt, $fontsize, 0e0, 10, 250, $str1); dump-res($err, @bound-rect);
$err = gdImageStringFT($im, @bound-rect, $red , $fontalt, $fontsize, 0e0, 10, 300, $str2); dump-res($err, @bound-rect);

my $fh = fopen("$name.png", "wb");
return 0 unless $fh;
gdImagePng($im, $fh);
fclose($fh) if $fh;

my $png-data;
my int32 $size;
my $ptr  = gdImagePngPtr($im, $size);
my $blob = blob-from-pointer($ptr, elems => $size, type => Blob[int8]);
my $png  =  MIME::Base64.encode($blob);
gdFree($ptr);
"$name.html".IO.spurt(qq :to/EOF/);
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF

sub dump-res($msg, @bound-rect) {
  if $msg {
    print "*** $msg\n";
  }
  else {
    print join(' ', |@bound-rect.map({ sprintf '%3d', $_ }), "\n");
  }
}

=begin POD

=head1 NAME

05-free-type.raku - drawing text using Free Type fonts

=head1 SYNOPSIS

  raku    05-free-type.raku
  display 05-free-type.png
  firefox 05-free-type.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing  various texts using Free Type (or True Type) fonts.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Raku modules C<GD::Raw> and C<MIME::Base64>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end POD
