#!/usr/bin/env raku
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec du texte utilisant Free Type
# Drawing text using Free Type fonts
#

use GD::Raw;
use MIME::Base64;
use NativeCall;
use NativeHelpers::Blob;

my $name   = '08-bounding-box';
my $width  = 500;
my $height = 400;
my $im     = gdImageCreate($width, $height);
LEAVE gdImageDestroy($im) if $im;
my $white  = gdImageColorAllocate($im, 255, 255, 255);
my $black  = gdImageColorAllocate($im,   0,   0,   0);
my $red    = gdImageColorAllocate($im, 255,   0,   0);
my $blue   = gdImageColorAllocate($im,   0,   0, 255);
my $grey-opaque   = gdImageColorAllocate($im, 224, 224, 224);

my $fontpath = "Sans";
my $fontalt  = "Serif";
my $fontsize = 10e0;

my $rc = gdFontCacheSetup();
LEAVE gdFontCacheShutdown();
# 1: use generic font names
my $config = gdFTUseFontConfig(1);

my @bound-rect := CArray[int32].new;
@bound-rect[7] = 0; # to allocate room for 8 integers

my $err;
$err = string-with-bg($im, $black, $grey-opaque, $fontpath, $fontsize,  π/2, 20, 110, "Vertical climb");
$err = string-with-bg($im, $black, $grey-opaque, $fontpath, $fontsize,  π/4, 30, 120, "Zoom climb"    );
$err = string-with-bg($im, $black, $grey-opaque, $fontpath, $fontsize,  0e0, 40, 130, "Level flight"  );
$err = string-with-bg($im, $black, $grey-opaque, $fontpath, $fontsize, -π/4, 30, 140, "Steep dive"    );
$err = string-with-bg($im, $black, $grey-opaque, $fontpath, $fontsize, -π/2, 20, 150, "Vertical dive" );

my $str1 = q :to<EOF>;
À l'Haÿ-les-Roses, rue Valentin Haüy,
vous êtes à côté de l'abîme où des pâtres naïfs
brûlèrent çà et là des œufs de Pâques à Noël.
EOF
my $str2 = q :to<EOF>;
Pfffff ! Lorsque le souffle du vent
fléchit dans le fjord, il est en effet
difficile de se faufiler.
EOF

$err = string-with-bg($im, $blue, $grey-opaque, $fontalt, $fontsize, 0e0, 10, 250, $str1);
$err = string-with-bg($im, $red , $grey-opaque, $fontalt, $fontsize, 0e0, 10, 300, $str2);

my $fh = fopen("$name.png", "wb");
return 0 unless $fh;
gdImagePng($im, $fh);
fclose($fh) if $fh;

my $png-data;
my int32 $size;
my $ptr  = gdImagePngPtr($im, $size);
my $blob = blob-from-pointer($ptr, elems => $size, type => Blob[int8]);
my $png  =  MIME::Base64.encode($blob);
gdFree($ptr);
"$name.html".IO.spurt(qq :to/EOF/);
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF

sub string-with-bg($im is rw, $ink, $bg, $fontpath, $fontsize, $angle, $x, $y, $str) {
  my @bound-rect := CArray[int32].new;
  @bound-rect[7] = 0; # to allocate room for 8 integers

  my $err = gdImageStringFT($im, @bound-rect, $ink, $fontpath, $fontsize, $angle, $x, $y, $str);
  return $err if $err;

  my @points;
  for 0..3 -> $i {
    @points[$i]   = gdPointPtr.new;
    @points[$i].x = @bound-rect[2 × $i];
    @points[$i].y = @bound-rect[2 × $i + 1];
  }
  gdImageFilledPolygon($im, @points, 4, $grey-opaque);
  $err = gdImageStringFT($im, @bound-rect, $ink, $fontpath, $fontsize, $angle, $x, $y, $str);

  return $err;
}

=begin POD

=head1 NAME

08-bounding-box.raku - drawing text using Free Type fonts

=head1 SYNOPSIS

  raku    08-bounding-box.raku
  display 08-bounding-box.png
  firefox 08-bounding-box.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing various texts using Free Type  (or True Type) fonts. The texts
appear on  a light grey  background, reflecting the bounding  boxes of
the texts.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Raku modules C<GD::Raw> and C<MIME::Base64>.

=head1 PROBLEMS AND ISSUES

When drawing the bounding box with an opaque colour, you need a 3-step
process:

  my $err = gdImageStringFT($im, @bound-rect, $black, $fontpath, $fontsize, $angle, $x, $y, $str); # 1
  gdImageFilledPolygon($im, @points, 4, $grey-opaque);                                             # 2
  $err    = gdImageStringFT($im, @bound-rect, $black, $fontpath, $fontsize, $angle, $x, $y, $str); # 3

If, between  step 1 and  step 3, another  process installs a  new Free
Type font, the bounding box in step  3 can be quite different from the
bounding  box  computed in  step  1.  The polygon  in  step  2 can  be
ill-fitting to the text in step 3.

To prevent this race condition, you need to use a colour with an alpha
channel.  This  cannot  be  done in  current  version  (0.7),  because
C<gdImageColorAllocateAlpha> is not ported yet to C<GD::Raw>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end POD
