#/usr/bin/env raku
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec des lignes en pointillés
# Drawing dotted lines
#

use GD;
use MIME::Base64;

my $name   = '02-dotted-lines';
my $width  = 120;
my $height =  50;
my $im     = GD::Image.new($width, $height);
my $white  = $im.colorAllocate(red => 255, green => 255, blue => 255);
my $black  = $im.colorAllocate(red =>   0, green =>   0, blue =>   0);
my $red    = $im.colorAllocate(red => 255, green =>   0, blue =>   0);
my $blue   = $im.colorAllocate(red =>   0, green =>   0, blue => 255);

$im.setStyle(style => [$red, $red, GD::gdTransparent, GD::gdTransparent]);
$im.line(start => (10, 10), end => (100, 10), color => GD::gdStyled);
$im.setStyle(style => [$blue, $blue, $blue, $blue, $blue, $blue, GD::gdTransparent, GD::gdTransparent, GD::gdTransparent, GD::gdTransparent, GD::gdTransparent, GD::gdTransparent]);
$im.line(start => (10, 20), end => (100, 20), color => GD::gdStyled);
$im.line(start => (10, 30), end => (100, 40), color => GD::gdStyled);

my $png_fh = $im.open("$name.png", "wb");
$im.output($png_fh, GD_PNG);
$png_fh.close;

#my $png =  MIME::Base64.encode($im.png);
my $png =  qx/base64 wip.png/;
"$name.html".IO.spurt(qq :to/EOF/);
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF

=begin POD

=head1 NAME

02-dotted-lines.raku - draw dotted lines

=head1 SYNOPSIS

  raku    02-dotted-lines.raku
  display 02-dotted-lines.png
  firefox 02-dotted-lines.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing  dotted lines.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Raku modules C<GD> and C<MIME::Base64>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end POD
