#!/usr/bin/env perl
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec des lignes en pointillés
# Drawing dotted lines
#

use v5.10;
use strict;
use warnings;
use GD;
use MIME::Base64;

my $name = '02-dotted-lines';
my $width  = 120;
my $height =  50;
my $im     = GD::Image->new($width, $height);
my $white  = $im->colorAllocate(255, 255, 255);
my $black  = $im->colorAllocate(  0,   0,   0);
my $red    = $im->colorAllocate(255,   0,   0);
my $blue   = $im->colorAllocate(  0,   0, 255);

$im->setStyle($red, $red, gdTransparent, gdTransparent);
$im->line(10, 10, 100, 10, gdStyled);
$im->setStyle(($blue) x 6, (gdTransparent) x 6);
$im->line(10, 20, 100, 20, gdStyled);
$im->line(10, 30, 100, 40, gdStyled);

open my $fh, '>', "$name.png"
    or die "opening PNG file: $!";
binmode $fh;
print $fh $im->png;
close $fh
    or die "closing PNG file: $!";

my $png =  MIME::Base64::encode($im->png);
open $fh, '>', "$name.html"
    or die "opening HTML file: $!";
print $fh <<"EOF";
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF
close $fh
    or die "closing HTML file: $!";


__END__

=encoding utf8

=head1 NAME

02-dotted-lines.pl - draw dotted lines

=head1 SYNOPSIS

  perl    02-dotted-lines.pl
  display 02-dotted-lines.png
  firefox 02-dotted-lines.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing  dotted lines.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Modules C<GD> and C<MIME::Base64>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end pod
