#!/usr/bin/env perl
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec des cercles et des rectangles plus du texte
# Drawing circles and rectangles with labels
#

use v5.10;
use strict;
use warnings;
use GD;
use MIME::Base64;

my $name   = '04-labels';
my $width  = 220;
my $height = 100;
my $im     = GD::Image->new($width, $height);
my $white  = $im->colorAllocate(255, 255, 255);
my $black  = $im->colorAllocate(  0,   0,   0);
my $red    = $im->colorAllocate(255,   0,   0);
my $blue   = $im->colorAllocate(  0,   0, 255);

$im->line(0, 10, 190, 30, $black);
$im->filledEllipse  ( 10, 20,  20, 20, $white);
$im->ellipse        ( 10, 20,  20, 20, $blue);
$im->filledRectangle( 30, 10,  50, 30, $white);
$im->rectangle      ( 30, 10,  50, 30, $blue);
$im->filledEllipse  ( 70, 20,  20, 20, $red);
$im->filledRectangle( 90, 10, 110, 30, $red);
$im->setThickness(3);
$im->filledEllipse  (130, 20,  20, 20, $white);
$im->ellipse        (130, 20,  20, 20, $blue);
$im->filledRectangle(150, 10, 170, 30, $white);
$im->rectangle      (150, 10, 170, 30, $blue);
$im->string(gdSmallFont     ,   5, 15, '01', $black);
$im->string(gdMediumBoldFont,  35, 15, '02', $black);
$im->string(gdLargeFont     , 153, 13, '03', $black);
$im->stringUp(gdLargeFont   , 200, 70, 'GOING UP', $black);

open my $fh, '>', "$name.png"
    or die "opening PNG file: $!";
binmode $fh;
print $fh $im->png;
close $fh
    or die "closing PNG file: $!";

my $png =  MIME::Base64::encode($im->png);
open $fh, '>', "$name.html"
    or die "opening HTML file: $!";
print $fh <<"EOF";
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF
close $fh
    or die "closing HTML file: $!";


__END__

=encoding utf8

=head1 NAME

04-labels.pl - print labels inside circles and rectangles

=head1 SYNOPSIS

  perl    04-labels.pl
  display 04-labels.png
  firefox 04-labels.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing  circles and  rectangles (or  squares) and  labels inside  the
circles and rectangles.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Modules C<GD> and C<MIME::Base64>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end pod
