#/usr/bin/env perl
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec du texte utilisant Free Type
# Drawing text using Free Type fonts
#

use v5.10;
use strict;
use warnings;
use GD;
use MIME::Base64;

my $name   = '05-free-type';
my $width  = 500;
my $height = 420;
my $im     = GD::Image->new($width, $height);
my $white  = $im->colorAllocate(255, 255, 255);
my $black  = $im->colorAllocate(  0,   0,   0);
my $red    = $im->colorAllocate(255,   0,   0);
my $blue   = $im->colorAllocate(  0,   0, 255);
my $fontpath = "/usr/share/fonts/truetype/freefont/FreeSans.ttf";
my $fontalt  = "/usr/share/fonts/truetype/freefont/FreeSerif.ttf";
my $fontsize = 10;
my $pi       = 4 * atan2(1, 1);
my @result;

# zero: do not use generic font names
my $config = $im->useFontConfig(0);

@result = $im->stringFT($black, $fontpath, $fontsize,   $pi / 2, 20, 110, "Vertical climb"); dump_res(@result);
@result = $im->stringFT($black, $fontpath, $fontsize,   $pi / 4, 30, 120, "Zoom climb");     dump_res(@result);
@result = $im->stringFT($black, $fontpath, $fontsize,   0      , 40, 130, "Level flight");   dump_res(@result);
@result = $im->stringFT($black, $fontpath, $fontsize, - $pi / 4, 30, 140, "Steep dive");     dump_res(@result);
@result = $im->stringFT($black, $fontpath, $fontsize, - $pi / 2, 20, 150, "Vertical dive");  dump_res(@result);

my $str1 = <<'EOF';
À l'Haÿ-les-Roses, rue Valentin Haüy,
vous êtes à côté de l'abîme où des pâtres naïfs
brûlèrent çà et là des œufs de Pâques à Noël.
EOF
my $str2 = <<'EOF';
Pfffff ! Lorsque le souffle du vent
fléchit dans le fjord, il est en effet
difficile de se faufiler.
EOF
@result = $im->stringFT($blue, $fontalt , $fontsize, 0,  10, 250, $str1);                         dump_res(@result);
@result = $im->stringFT($blue, $fontalt , $fontsize, 0,  10, 310, $str1, { linespacing => 0.8 }); dump_res(@result);
@result = $im->stringFT($blue, $fontalt , $fontsize, 0,  10, 360, $str1, { linespacing => 1.3 }); dump_res(@result);
@result = $im->stringFT($red , $fontalt , $fontsize, 0, 270, 250, $str2, { kerning => 0 });       dump_res(@result);
@result = $im->stringFT($red , $fontalt , $fontsize, 0, 270, 310, $str2, { kerning => 1 });       dump_res(@result);

open my $fh, '>', "$name.png"
    or die "opening PNG file: $!";
binmode $fh;
print $fh $im->png;
close $fh
    or die "closing PNG file: $!";

my $png =  MIME::Base64::encode($im->png);
open $fh, '>', "$name.html"
    or die "opening HTML file: $!";
print $fh <<"EOF";
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF
close $fh
    or die "closing HTML file: $!";

sub dump_res {
  if (@_) {
    my @res = map { sprintf('%3d', $_) } @_;
    print join ' ', @res, "\n";
  }
  else {
    print "**** $@\n";
  }
}

__END__

=encoding utf8

=head1 NAME

05-free-type.pl - drawing text using Free Type fonts

=head1 SYNOPSIS

  perl    05-free-type.pl
  display 05-free-type.png
  firefox 05-free-type.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing  various texts using Free Type (or True Type) fonts.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Modules C<GD> and C<MIME::Base64>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end pod
