#/usr/bin/env perl
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec du texte utilisant Free Type
# Drawing circles and rectangles with labels
#

use v5.10;
use strict;
use warnings;
use GD;
use MIME::Base64;

my $name   = '05-free-type';
my $width  = 500;
my $height = 350;
my $im     = GD::Image->new($width, $height);
my $white  = $im->colorAllocate(255, 255, 255);
my $black  = $im->colorAllocate(  0,   0,   0);
my $red    = $im->colorAllocate(255,   0,   0);
my $blue   = $im->colorAllocate(  0,   0, 255);
my $fontpath = "/usr/share/fonts/truetype/freefont/FreeSans.ttf";
my $fontalt  = "/usr/share/fonts/truetype/freefont/FreeSerif.ttf";
my $fontsize = 10;
my $pi       = 4 * atan2(1, 1);

$im->stringFT($black, $fontpath, $fontsize,   $pi / 2, 10, 110, "Vertical climb");
$im->stringFT($black, $fontpath, $fontsize,   $pi / 4, 20, 120, "Zoom climb");
$im->stringFT($black, $fontpath, $fontsize,   0      , 30, 130, "Level flight");
$im->stringFT($black, $fontpath, $fontsize, - $pi / 4, 20, 140, "Steep dive");
$im->stringFT($black, $fontpath, $fontsize, - $pi / 2, 10, 150, "Vertical dive");

$im->stringFTCircle(300, 130, 100, 20, 0.7, $fontpath, 10, "wingover", "resource", $black);

my $str1 = <<'EOF';
Vous êtes à côté de l'abîme où des pâtres naïfs
brûlèrent çà et là des œufs de Pâques à Noël.
EOF
my $str2 = <<'EOF';
Pfffff ! Lorsque le souffle du vent
fléchit dans le fjord, il est en effet
difficile de se faufiler.
EOF
$im->stringFT($blue, $fontalt , $fontsize, 0,  10, 250, $str1);
$im->stringFT($blue, $fontalt , $fontsize, 0,  10, 280, $str1, { linespacing => 0.8 });
$im->stringFT($blue, $fontalt , $fontsize, 0,  10, 310, $str1, { linespacing => 1.3 });
$im->stringFT($red , $fontalt , $fontsize, 0, 270, 250, $str2, { kerning => 0 });
$im->stringFT($red , $fontalt , $fontsize, 0, 270, 310, $str2, { kerning => 1 });

open my $fh, '>', "$name.png"
    or die "opening PNG file: $!";
binmode $fh;
print $fh $im->png;
close $fh
    or die "closing PNG file: $!";

my $png =  MIME::Base64::encode($im->png);
open $fh, '>', "$name.html"
    or die "opening HTML file: $!";
print $fh <<"EOF";
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF
close $fh
    or die "closing HTML file: $!";


__END__

=encoding utf8

=head1 NAME

05-free-type.pl - print labels inside circles and rectangles

=head1 SYNOPSIS

  perl    05-free-type.pl
  display 05-free-type.png
  firefox 05-free-type.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing  circles and  rectangles (or  squares) and  labels inside  the
circles and rectangles.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Modules C<GD> and C<MIME::Base64>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end pod
