#!/usr/bin/env perl
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec du texte utilisant Free Type
# Drawing text using Free Type fonts
#

use v5.10;
use strict;
use warnings;
use GD;
use MIME::Base64;

my $name   = '08-bounding-box';
my $width  = 550;
my $height = 450;
my $im     = GD::Image->newTrueColor($width, $height);
my $white  = $im->colorAllocate(255, 255, 255);
my $black  = $im->colorAllocate(  0,   0,   0);
my $red    = $im->colorAllocate(255,   0,   0);
my $blue   = $im->colorAllocate(  0,   0, 255);
my $grey_opaque   = $im->colorAllocateAlpha(224, 224, 224,   0);
my $grey_transp   = $im->colorAllocateAlpha(192, 192, 192,  64);
my $fontpath = "sans";
my $fontalt  = "serif";
my $fontsize = 10;
my $pi       = 4 * atan2(1, 1);
my @result;

# 1: use generic font names
my $config = $im->useFontConfig(1);

# True Color picture: you need to paint the background
$im->filledRectangle(0, 0, $width - 1, $height - 1, $white);

@result = $im->stringFT($black, $fontpath, $fontsize,   $pi / 2, 20, 110, "Vertical climb"); bounding(@result);
@result = $im->stringFT($black, $fontpath, $fontsize,   $pi / 4, 30, 120, "Zoom climb");     bounding(@result);
@result = $im->stringFT($black, $fontpath, $fontsize,   0      , 40, 130, "Level flight");   bounding(@result);
@result = $im->stringFT($black, $fontpath, $fontsize, - $pi / 4, 30, 140, "Steep dive");     bounding(@result);
@result = $im->stringFT($black, $fontpath, $fontsize, - $pi / 2, 20, 150, "Vertical dive");  bounding(@result);

my $str1 = <<'EOF';
À l'Haÿ-les-Roses, rue Valentin Haüy,
vous êtes à côté de l'abîme où des pâtres naïfs
brûlèrent çà et là des œufs de Pâques à Noël.
EOF
my $str2 = <<'EOF';
Pfffff ! Lorsque le souffle du vent
fléchit dans le fjord, il est en effet
difficile de se faufiler.
EOF

# No alpha channel: three-step process with possible race condition
@result = GD::Image->stringFT($blue, $fontalt , $fontsize, 0,  10, 250, $str1);
$im->filledRectangle(@result[0, 1, 4, 5], $grey_opaque);
@result = $im->stringFT($blue, $fontalt , $fontsize, 0,  10, 250, $str1);

# With alpha channel: two-step process, without race condition
@result = $im->stringFT($blue, $fontalt , $fontsize, 0,  10, 310, $str1, { linespacing => 0.8 });
$im->filledRectangle(@result[0, 1, 4, 5], $grey_transp);
@result = $im->stringFT($blue, $fontalt , $fontsize, 0,  10, 360, $str1, { linespacing => 1.3 });
$im->filledRectangle(@result[0, 1, 4, 5], $grey_transp);

@result = $im->stringFT($red , $fontalt , $fontsize, 0, 320, 250, $str2, { kerning => 0 });
@result = $im->stringFT($red , $fontalt , $fontsize, 0, 320, 310, $str2, { kerning => 1 });

open my $fh, '>', "$name.png"
    or die "opening PNG file: $!";
binmode $fh;
print $fh $im->png;
close $fh
    or die "closing PNG file: $!";

my $png =  MIME::Base64::encode($im->png);
open $fh, '>', "$name.html"
    or die "opening HTML file: $!";
print $fh <<"EOF";
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Graphic file</h1>
<img src='$name.png'>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF
close $fh
    or die "closing HTML file: $!";

sub dump_res {
  if (@_) {
    my @res = map { sprintf('%3d', $_) } @_;
    print join ' ', @res, "\n";
  }
  else {
    print "**** $@\n";
  }
}

sub bounding {
  my @angle = @_;
  my $poly = GD::Polygon->new;
  for my $i (0, 2, 4, 6) {
    $poly->addPt(@angle[$i, $i + 1]);
  }
  $im->filledPolygon($poly, $grey_transp);
}

__END__

=encoding utf8

=head1 NAME

08-bounding-box.pl - drawing text using Free Type fonts, on a light grey background

=head1 SYNOPSIS

  perl    08-bounding-box.pl
  display 08-bounding-box.png
  firefox 08-bounding-box.html

=head1 DESCRIPTION

This program  generates a  PNG file  and an HTML  file with  a picture
showing various texts using Free Type (or True Type) fonts. Some texts
appear on  a light grey  background, reflecting the bounding  boxes of
the texts.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Modules C<GD> and C<MIME::Base64>.

=head1 PROBLEMS AND ISSUES

When drawing the bounding box with an opaque colour, you need a 3-step
process:

  @bounds = GD::Image->stringFT(...); # 1
  $im->rectangle(..., $grey_opaque);  # 2
  @bounds = $im->stringFT(...);       # 3

If, between  step 1 and  step 3, another  process installs a  new Free
Type font, the bounding box in step  3 can be quite different from the
bounding  box computed  in step  1.  The rectangle  in step  2 can  be
ill-fitting  to the  text in  step  3. This  is a  race condition.  To
prevent  this race  condition, you  should use  colours with  an alpha
channel.

  @bounds = $im->stringFT(...);       # 1
  $im->rectangle(..., $grey_transp);  # 2

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end pod
