#!/usr/bin/env perl
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Dessin avec des lignes en pointillés
# Drawing dotted lines
#

use v5.10;
use strict;
use warnings;
use GD;
use MIME::Base64;

my $name = '060-styled';
my $width  = 120;
my $height = 100;
my $im     = GD::Image->new($width, $height);
my $white  = $im->colorAllocate(255, 255, 255);
my $black  = $im->colorAllocate(  0,   0,   0);
my $red    = $im->colorAllocate(255,   0,   0);
my $blue   = $im->colorAllocate(  0,   0, 255);

$im->setStyle($red, $red, gdTransparent, gdTransparent);
$im->line(     10, 10, 100, 10, gdStyled);
$im->rectangle(60, 50, 100, 60, gdStyled);
$im->setStyle(($blue) x 6, (gdTransparent) x 6);
$im->line(     10, 20, 100, 20, gdStyled);
$im->line(     10, 30, 100, 40, gdStyled);
$im->rectangle(10, 50,  50, 60, gdStyled);

my $poly = GD::Polygon->new;
$poly->addPt( 60, 70);
$poly->addPt(110, 80);
$poly->addPt( 60, 90);
$poly->addPt( 10, 80);
$im->openPolygon($poly, gdStyled);

my $png =  MIME::Base64::encode($im->png);
$png =~ s/\n\Z//;
open my $fh, '>', "$name.html"
    or die "opening HTML file: $!";
print $fh <<"EOF";
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
</body>
</html>
EOF
close $fh
    or die "closing HTML file: $!";


__END__

=encoding utf8

=head1 NAME

mk-test-style.pl - draw dotted lines to create a test file for Raku

=head1 SYNOPSIS

  perl    mk-test-style.pl
  firefox 060-styled.html

=head1 DESCRIPTION

This program generates a PNG file with a picture showing dotted lines.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Modules C<GD> and C<MIME::Base64>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end pod
