#/usr/bin/env perl
# -*- encoding: utf-8; indent-tabs-mode: nil -*-
#
# Génération d'un fichier de tests pour les fonctions gdImageXxxPtr
# Generating a test for functions gdImageXxxPtr
#

use v5.10;
use strict;
use warnings;
use GD;
use MIME::Base64;

my $name   = 'gd-image-xxx-ptr';
my $width  = 10;
my $height = 10;
my $im     = GD::Image->new($width, $height);
my $white  = $im->colorAllocate(255, 255, 255);
my $red    = $im->colorAllocate(255,   0,   0);
my $blue   = $im->colorAllocate(  0,   0, 255);

$im->line(0, 0, 9, 9, $red);
$im->line(9, 0, 0, 9, $blue);

my $png  =  $im->png;
my $png0 =  $im->png(0);
my $png9 =  $im->png(9);
my $jpeg =  $im->jpeg;
my $gif  =  $im->gif;
my $bmp  =  $im->bmp;
my $bmp1 =  $im->bmp(1);
for ($png, $png0, $png9, $jpeg, $gif, $bmp, $bmp1) {
  $_ = MIME::Base64::encode($_);
  s/\n\z//;      # because the Raku module does not add a newline at the end
}
open my $fh, '>', "$name.html"
    or die "opening HTML file: $!";
print $fh <<"EOF";
<html>
<head><title>Example of graphic file generated by GD</title></head>
<body>
<h1>Embedded PNG data</h1>
<img src='data:image/png;base64,$png'>
<h1>Embedded PNG data (compression 0)</h1>
<img src='data:image/png;base64,$png0'>
<h1>Embedded PNG data (compression 9)</h1>
<img src='data:image/png;base64,$png9'>
<h1>Embedded JPEG data</h1>
<img src='data:image/png;base64,$jpeg'>
<h1>Embedded GIF data</h1>
<img src='data:image/png;base64,$gif'>
<h1>Embedded BMP data</h1>
<img src='data:image/png;base64,$bmp'>
<h1>Embedded BMP data (RLE)</h1>
<img src='data:image/png;base64,$bmp1'>
</body>
</html>
EOF
close $fh
    or die "closing HTML file: $!";


__END__

=encoding utf8

=head1 NAME

mk-test-xxx-ptr.pl - Create a test file for functions C<gdImageXxxPtr>.

=head1 SYNOPSIS

  perl    mk-test-xxx-ptr.pl
  firefox gd-image-xxx-ptr.html

=head1 DESCRIPTION

This program generates  an HTML file with an  embedded picture showing
basic lines.  The picture  is shown with  several formats:  PNG, JPEG,
GIF, etc.

=head1 PARAMETERS

None.

=head1 PREREQUISITE

Modules C<GD> and C<MIME::Base64>.

=head1 AUTHOR

Jean Forget <J2N-FORGET at orange dot fr>

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2026 Jean Forget, all rights reserved

This program is free software; you can redistribute it and/or modify it under the Artistic License 2.0.

=end pod
